import type { Theme } from './types'

export const terminal: Theme = {
  name: 'terminal',
  // System monospace only: no bundled font files, no font licenses to ship.
  fonts: {
    display: "ui-monospace, 'SF Mono', Menlo, Consolas, 'Liberation Mono', monospace",
    body:    "ui-monospace, 'SF Mono', Menlo, Consolas, 'Liberation Mono', monospace",
    mono:    "ui-monospace, 'SF Mono', Menlo, Consolas, 'Liberation Mono', monospace",
  },
  light: {
    'bg':                   '#F4F6F3',
    'surface':              '#FFFFFF',
    'surface-2':            '#ECEFE9',
    'border':               '#D7DDD2',
    'text':                 '#15201A',
    'text-muted':           '#5C6B5E',
    'accent':               '#1A7F37',
    'accent-bg':            '#E4F0E2',
    'eval-positive':        '#1A7F37',
    'eval-negative':        '#C0392B',
    'live':                 '#E67E22',
    'live-bg':              '#FEF3E2',
    'move-highlight-bg':    '#E4F0E2',
    'move-highlight-text':  '#1A7F37',
    'nav-btn-bg':           '#ECEFE9',
    'nav-btn-border':       '#D7DDD2',
    'nav-btn-text':         '#5C6B5E',
    'nav-btn-active-bg':    '#1A7F37',
    'nav-btn-active-text':  '#FFFFFF',
    'board-surround':       '#E5E9E1',
    'board-surround-text':  '#15201A',
    'board-surround-subtext': 'rgba(21,32,26,0.45)',
    'eval-bar-white':       '#ffffff',
    'eval-bar-black':       '#1a1a1a',
    'eval-bar-bg':          '#2a2a2a',
    'on-colored':           '#FFFFFF',
    'hint-dot':             'rgba(0,0,0,0.20)',
    'hint-ring':            'rgba(192,57,43,0.60)',
    'hint-pickup':          'rgba(26,127,55,0.30)',
    'status-running':       '#C2410C',
    'glow-accent':          'none',
    'glow-dot':             'none',
    'gold':                 '#8A6200',
    'gold-bg':              '#FBF4DC',
    'glow-gold':            'none',
  },
  dark: {
    'bg':                   '#070A08',
    'surface':              '#0D120B',
    'surface-2':            '#121A10',
    'border':               '#2C3D25',
    'text':                 '#DCEFD4',
    'text-muted':           '#88AC8D',
    'accent':               '#46E25C',
    'accent-bg':            '#0F2A12',
    'eval-positive':        '#46E25C',
    'eval-negative':        '#FF5B47',
    'live':                 '#FF9500',
    'live-bg':              '#1C1200',
    'move-highlight-bg':    '#0F2A12',
    'move-highlight-text':  '#46E25C',
    'nav-btn-bg':           '#121A10',
    'nav-btn-border':       '#2C3D25',
    'nav-btn-text':         '#7CA081',
    'nav-btn-active-bg':    '#46E25C',
    'nav-btn-active-text':  '#04140A',
    'board-surround':       '#0A0E0A',
    'board-surround-text':  '#DCEFD4',
    'board-surround-subtext': 'rgba(220,239,212,0.5)',
    'eval-bar-white':       '#ffffff',
    'eval-bar-black':       '#070A08',
    'eval-bar-bg':          '#040706',
    'on-colored':           '#04140A',
    'hint-dot':             'rgba(255,255,255,0.22)',
    'hint-ring':            'rgba(255,91,71,0.65)',
    'hint-pickup':          'rgba(70,226,92,0.30)',
    'status-running':       '#FFB13A',
    'glow-accent':          '0 0 8px rgba(70,226,92,0.35)',
    'glow-dot':             '0 0 5px currentColor',
    'gold':                 '#F5C542',
    'gold-bg':              '#1C1705',
    'glow-gold':            'inset 0 0 0.875rem rgba(245,197,66,0.22)',
  },
}
